name: Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag"
        required: true
        type: string

jobs:
  release_test:
    name: (Release) Test release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - run: pipx install poetry

      - run: poetry install --with test
        working-directory: server

      - run: poetry run pytest -v --postgres --mysql .
        working-directory: server

      - run: |
          docker build -t greener-test:latest ..
          python -m venv .venv
          .venv/bin/python -m pip install -r requirements.txt
          .venv/bin/python -m pytest -v --skip-sqlite
        working-directory: tests_e2e

  release_create:
    name: (Release) Create release
    needs: release_test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    environment: Docker Hub
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Prepare image tag
        run: |
          GREENER_IMAGE_TAG="${{ inputs.release_tag }}"
          GREENER_IMAGE_TAG="$(echo "$GREENER_IMAGE_TAG" | cut -c2-)"
          echo "GREENER_IMAGE_TAG=$GREENER_IMAGE_TAG" >> $GITHUB_ENV

      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: cephei8/greener:${{ env.GREENER_IMAGE_TAG }}, cephei8/greener:latest
          platforms: linux/amd64,linux/arm64

      - name: Create release
        run: |
          gh release create ${{ inputs.release_tag }}
        env:
          GH_TOKEN: ${{ github.token }}
